import tkinter

m = tkinter.Tk()

menu1 = tkinter.Menu(m)
m.config(menu=menu1)
m.geometry('400x400')
filemenu = tkinter.Menu(menu1,tearoff=0)

menu1.add_cascade(label='File', menu = filemenu)

filemenu.add_command(label='New Text File')
filemenu.add_command(label='New File...')
filemenu.add_command(label='New Window')
filemenu.add_command(label='New Window With Profile')
filemenu.add_separator()
filemenu.add_command(label='Open File...')
filemenu.add_command(label='Open Folder...')
filemenu.add_command(label='Open Workspace from File...')
filemenu.add_command(label='Open Recent...')
filemenu.add_separator()
filemenu.add_command(label='Add Folder to Workspace...')
filemenu.add_command(label='Save Workspace As...')
filemenu.add_command(label='Duplicate Workspace')
filemenu.add_separator()
filemenu.add_command(label='Save')
filemenu.add_command(label='Save As...')
filemenu.add_command(label='Save All')
filemenu.add_separator()
filemenu.add_command(label='Share')
filemenu.add_separator()
filemenu.add_command(label='Auto Save')
filemenu.add_command(label='Preferences')
filemenu.add_separator()
filemenu.add_command(label='Revert File')
filemenu.add_command(label='Close Editor')
filemenu.add_command(label='Close Folder')
filemenu.add_command(label='Close Window')
filemenu.add_separator()
filemenu.add_command(label='Exit', command=m.destroy)

menu2=tkinter.Menu(m)
m.config(menu=menu1)
editmenu= tkinter.Menu(menu1,tearoff=0)

menu1.add_cascade(label='Edit', menu = editmenu)

editmenu.add_command(label='Undo')
editmenu.add_command(label='Redo')
editmenu.add_separator()
editmenu.add_command(label='Cut')
editmenu.add_command(label='Copy')
editmenu.add_command(label='Paste')
editmenu.add_separator()
editmenu.add_command(label='Find')
editmenu.add_command(label='Replace')
editmenu.add_separator()
editmenu.add_command(label='Find in Files')
editmenu.add_command(label='Replace in Files')
editmenu.add_separator()
editmenu.add_command(label='Toggle Line Comment')
editmenu.add_command(label='Toggle Block Comment')
editmenu.add_command(label='Emmet: Expand Abbreviation')

menu3=tkinter.Menu(m)
m.config(menu=menu1)
selectionmenu= tkinter.Menu(menu1,tearoff=0)

menu1.add_cascade(label='Selection', menu=selectionmenu)

selectionmenu.add_command(label='Select All')
selectionmenu.add_command(label='Expand Selection')
selectionmenu.add_command(label='Shrink Selection')
selectionmenu.add_separator()
selectionmenu.add_command(label='Copy Line Up')
selectionmenu.add_command(label='Copy Line Down')
selectionmenu.add_command(label='Move Line Up')
selectionmenu.add_command(label='Move Line Down')
selectionmenu.add_command(label='Duplicate Selection')
selectionmenu.add_separator()
selectionmenu.add_command(label='Add Cursor Above')
selectionmenu.add_command(label='Add Cursor Below')
selectionmenu.add_command(label='Add Cursors to Line Ends')
selectionmenu.add_command(label='Add Next Occurrence')
selectionmenu.add_command(label='Add Previous Occurrence')
selectionmenu.add_command(label='Select All Ocurrences')
selectionmenu.add_separator()
selectionmenu.add_command(label='Switch to Ctrl+Click for Multi-Cursor')
selectionmenu.add_command(label='Column Selection Mode')


m.mainloop()
